export enum ClassLanguages {
    'NEDERLANDS' = "LIBRARY.CLASS.CREATE.LANGUAGE.NEDERLANDS",
    'ENGELS' = "LIBRARY.CLASS.CREATE.LANGUAGE.ENGELS",
    'SPAANS' = "LIBRARY.CLASS.CREATE.LANGUAGE.SPAANS",
    
  }
  