export enum EducationalCourses {
  'COMMUNICATION' = 'LIBRARY.ITEM_OVERVIEW.COMMUNICATION',
  'EDUCATIONAL' = 'LIBRARY.ITEM_OVERVIEW.EDUCATIONAL',
  'ENGLISH' = 'LIBRARY.ITEM_OVERVIEW.ENGLISH',
  'GAMES' = 'LIBRARY.ITEM_OVERVIEW.GAMES',
  'GEOGRAPHY' = 'LIBRARY.ITEM_OVERVIEW.GEOGRAPHY',
  'MATHEMATICS' = 'LIBRARY.ITEM_OVERVIEW.MATHEMATICS',
  'MUSIC' = 'LIBRARY.ITEM_OVERVIEW.MUSIC',
  'ROBOTICS' = 'LIBRARY.ITEM_OVERVIEW.ROBOTICS',
  'SOCIO EDUCATIONAL ACTIVITIES' = 'LIBRARY.ITEM_OVERVIEW.SOCIO_EDUCATIONAL_ACTIVITIES',
  'STIMULATION' = 'LIBRARY.ITEM_OVERVIEW.STIMULATION',
}
